# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=140)),
                ('HasSubcategory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=140)),
                ('ConsolidatedRating', models.SmallIntegerField(blank=True)),
                ('Description', models.TextField(blank=True)),
                ('Tutorials', models.TextField(blank=True)),
                ('IsBest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=140)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('UserID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('IPAddress', models.GenericIPAddressField(unique=True)),
                ('Rating', models.SmallIntegerField()),
                ('searchresult', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.SearchResult')),
            ],
        ),
        migrations.AddField(
            model_name='searchresult',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Subcategory'),
        ),
    ]
